spring.application.name=comicverse

# Configurazione per la tua classe HibernateConfiguration
db.driver=oracle.jdbc.driver.OracleDriver
db.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
db.username=comicverse
db.password=VladimiroEr_Carbonaro

hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
hibernate.show_sql=true
hibernate.hbm2ddl.auto=validate
entitymanager.packagesToScan=com.dgsspa.comicverse.model

spring.profiles.active=dev

search.messages.no-results=Nessun fumetto trovato per il criterio: %s
errors.not-found.fumetto-id=Fumetto non trovato con id: %s
messages.success.deleted=%s con id %s eliminato correttamente
